DBあり一覧表示機能実装
sasaoka-sasami/python-memoapp pull request #3
Opened 2024-11-27 04:11 UTC by sasaoka-sasami

## 事前資料

* 該当レビュー用スレッドを参照

## やったこと

* 一覧表示機能にDBとの接続、DBに登録されているデータを取得して表示する工程を追加実装しました

## やらないこと

* app.pyのinitialize_errorの回収はログイン機能実装時に行います

## できるようになること（ユーザ目線）

*アプリに登録されているメモを一覧で見ることができる

## 動作確認

* DBにメモが登録されている場合/メモが1件も登録されていない場合/データベースサーバが停止している場合(DBエラーの確認)の3パターンでweb上での表示を確認しました(「動作パターン：期待する結果」の表記としています)
* DBにメモ登録がある場合：メモが表示される
<img width="960" alt="test_メモあり_1127" src="https://github.com/user-attachments/assets/409bdaa9-7b77-49dd-8c05-253b6907e870">
* DBにメモ登録がない場合：「メモは登録されていません」と表示される
<img width="960" alt="test_メモ無し_1127" src="https://github.com/user-attachments/assets/1b5c9772-b246-438b-8ef0-386d890fe260">
* DBエラー：「8000：データが取得できませんでした」と表示される
<img width="960" alt="test_DBエラー_1127" src="https://github.com/user-attachments/assets/c563978f-6e98-4cfc-aaf8-4d47b9b0aabe">

## その他

* 無し

2024-11-27 05:02 UTC, nozomi-suzuki2022 commented
中身のレビューに入る前に、プルリク自体に対するコメントを何点か書かせていただきます。

- プルリクに記載いただく内容
  - 前回のプルリクから「やったこと」「できるようになること」などの項目が増えたことでプルリク自体の目的などが分かりやすくなってきて良いと思います！
  - さらに良くするとしたら、「事前資料」のリンクもプルリク内に記載して、プルリクから全ての情報が追えるとよりレビューしやすくなるかと思います。office系のファイルはリンクのコピーができるので、そのリンクを置けばアクセス権がある人だけ見られるはずなので安全に共有できるかと思います。（Teamsにはプルリクのリンクだけ共有して、情報は全てプルリクに記載する、のように役割分担しておくと行ったり来たりがなくて便利かと思います）
  - 要件定義書を事前資料として記載いただいてると思うのですが、こちらのどこが今回のプルリクに関連しているかが少し探しづらいので、ページ数などを一緒に書いていただくと親切かもしれません。

- app.py でコンフリクトが発生していると出ているので、こちらの解消をお願いします。
![image](https://github.com/user-attachments/assets/6081e682-bfe5-4e36-a549-821fd1b886e6)

コンフリクトの解消はちょっと難しいかもしれないので、誰かに一緒にやってもらうのも手かもしれないです。
上記の内容で分からないことがあればぜひ質問してみてください！

2024-11-27 05:35 UTC, sasaoka-sasami commented
@nozomi-suzuki2022 
お疲れ様です！コメントありがとうございます。

- プルリク記載内容
  - 事前資料のリンクについては、コーチャー確認の元機密に関連するものは控えたいということで、載せない判断となりました。画面往復になって大変になってしまうかと思うのですが、よろしくお願いいたします。
  - ページ数の考えは抜けていました！teams依頼スレッドの方に関連しそうなページ番号を表記いたしました。

- コンフリクトについて
 - 色々調べて解消できた……と思います。確認したのですが、不備がありそうな場合にはもう一度ご連絡ください。
 
プルリクの出し方そのものは良い方に改善できていそうで安心しました！ありがとうございます。

2024-11-27 06:02 UTC, nozomi-suzuki2022 commented
- 事前資料のリンクについて承知いたしました。コーチャーに確認して判断できてて良いと思います！
- コンフリクトもGitHub上では解消されていそうなので大丈夫そうです！対応ありがとうございます。

2024-11-27 06:40 UTC, nozomi-suzuki2022 commented on templates/display-all-memos.html
> +        <p style="color: red;">{{error_message}}：データが取得できませんでした</p>
動作確認のスクショを見ると、error_message の部分に8000と来ていてぱっと見エラーコードっぽいですが、これがユーザーに見えるメリットはありますか？
8000と表示されても何のことかな、直感的に疑問に感じてしまい...
エラーメッセージで状況は伝えているので、ここはメッセージだけの表示でも良いかと思います。

2024-11-27 06:42 UTC, nozomi-suzuki2022 commented on templates/displya-all-memos.html
こちらファイルが重複していますね...

2024-11-27 08:05 UTC, TomoharuSakuma commented
プルリク自体についての軽微なコメントです
おそらくこのあたりは箇条書きにしたかったんだと思いますが、うまくいっていませんね
Preview タブがあると思うので、それでどのように見えるのか確認しながら作成をお願いします

|![image](https://github.com/user-attachments/assets/c107ec95-cf85-4041-9a71-3a2be22229af)|
|:-:|

|![image](https://github.com/user-attachments/assets/9cb75c76-6e2e-4f79-8f22-9c67109e8563)|
|:-:|

2024-11-28 05:10 UTC, sasaoka-sasami commented
@TomoharuSakuma 
確認漏れです。すみません。
修正しました！よろしくお願いいたします。

2024-11-28 05:16 UTC, sasaoka-sasami commented on templates/display-all-memos.html
> +        <p style="color: red;">{{error_message}}：データが取得できませんでした</p>
確かにエラーコードはユーザーに見えなくてもいいですね……
エラーコード削除、メッセージのみ表示で修正対応いたしました。

2024-11-28 05:17 UTC, sasaoka-sasami commented on templates/displya-all-memos.html
ファイル名のスペルが間違っていたために、コンフリクト解消時に2つ出来上がったものと思われます。
片方削除いたしました。

2024-11-28 05:18 UTC, sasaoka-sasami commented
@nozomi-suzuki2022 
コメントありがとうございます！
作ったときのgitコマンドミスで名前からfeature/が消えてしまいました……
gitコマンドを積極的に使用して慣れていきます。次回よりブランチ名は反映させていきます。

2024-11-28 05:38 UTC, nozomi-suzuki2022 commented on templates/display-all-memos.html
> +        <p style="color: red;">{{error_message}}：データが取得できませんでした</p>
修正ありがとうございます！
プルリクの説明部分の動作確認スクショも合わせて変更お願いしますー

2024-11-28 05:45 UTC, sasaoka-sasami commented on templates/display-all-memos.html
> +        <p style="color: red;">{{error_message}}：データが取得できませんでした</p>
失礼しました。こちら動作確認結果になります。
<img width="960" alt="test_DBエラー_1128" src="https://github.com/user-attachments/assets/2fae13d8-4d42-45a6-8401-214c0570bf10">

2024-11-28 05:50 UTC, nozomi-suzuki2022 commented on templates/display-all-memos.html
> +        <p style="color: red;">{{error_message}}：データが取得できませんでした</p>
ん...？プルリクの最初の説明って編集できない感じですかね...？
まあでも↑に載せていただいたもので確認できたのでOKです！

2024-11-28 05:51 UTC, nozomi-suzuki2022 approved these changes
もう後は指摘ないのでOKです！承認しますー

2024-11-28 06:37 UTC, TomoharuSakuma requested changes

2024-11-28 06:38 UTC, TomoharuSakuma commented
> @TomoharuSakuma コメントありがとうございます！ 確認漏れです。すみません。 修正しました！よろしくお願いいたします。

この部分はこれであってますか？箇条書きにしたいのかなと思ったのですが
> *アプリに登録されているメモを一覧で見ることができる

2024-11-28 06:43 UTC, sasaoka-sasami commented on app.py
> +from flask import Flask, g
試行錯誤の名残です。削除しました。

2024-11-28 07:02 UTC, sasaoka-sasami commented on app.py
> +app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:postgres@localhost:5432/memoappdb'
フォーマッタ導入タイミングを考えていましたが、これを機に入れてみました！クォーテーションも修正いたしました。

2024-11-28 07:06 UTC, sasaoka-sasami commented
@TomoharuSakuma 
プルリク詳細の箇条書き部分修正いたしました。
修正途中で1回キャンセルしたので反映されてなかったようです。失礼しました。

2024-11-28 07:11 UTC, TomoharuSakuma approved these changes

2024-11-28 07:17 UTC, merged